### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by The-Daishogun** [isogand/github#1]
According to [yarn documentation](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) ./yarn/cache/* folder should not be committed to the repo

consider adding the folders mentioned in the documentation to your .gitignore file

**Comment by isogand** [comment]
Hi, thank you for creating this issue.

However there is no such folder committed.

Updated the gitignore file just in case.
https://github.com/isogand/github

**Comment by The-Daishogun** [comment]
Thank you for the response.
